Ensure x86_64 processor architecture is listed as supported
pi-hole/pi-hole pull request #3890
Opened 2020-12-01 22:57 UTC by ganto

**By submitting this pull request, I confirm the following:** 
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
Currently the Pi-hole debug script running on a regular 64bit Intel/AMD processor doesn't display the architecture as supported:
```
*** [ DIAGNOSING ]: Processor                                                                                                                                  
[i] x86_64
```

**How does this PR accomplish the above?:**
Ensure that the usual output of `uname -m` for Intel-compatible 64bit processors is recognized as supported. With my change:
```
*** [ DIAGNOSING ]: Processor                                                                                                                                  
[✓] x86_64
```
I even think that the already defined value `amd64` is invalid and never returned by `uname` or `lscpu`. But maybe there are somewhere some exotic kernel builds so I don't dare to break anything existing that might work. 

**What documentation changes (if any) are needed to support this PR?:**
None

---

2020-12-01 23:27 UTC, dschaper requested changes

2020-12-01 23:27 UTC, dschaper commented on advanced/Scripts/piholeDebug.sh
> +                ;;
```suggestion
            "amd64" | "x86_64") log_write "${TICK} ${COL_GREEN}${PROCESSOR}${COL_NC}"
                ;;
```

2020-12-01 23:30 UTC, dschaper commented on advanced/Scripts/piholeDebug.sh
> +                ;;
Just to keep 64bit platforms on the same line.

2020-12-02 19:24 UTC, ganto commented
Ok, done. I thought it's easier to read the other way around but that's fine too.

Do you want me to rebase the two commits into one?

2020-12-02 19:26 UTC, dschaper commented
You can squash and force-push if you'd like.

2020-12-02 20:53 UTC, PromoFaux approved these changes

2020-12-02 21:09 UTC, PromoFaux approved these changes

2020-12-02 21:12 UTC, merged