Replace calls to sqlite3 by calls to pihole-FTL sqlite3
pi-hole/pi-hole pull request #4584
Opened 2022-01-30 09:54 UTC by DL6ER

**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Solve issues with ancient system-provided SQLite3 version as this is limiting us and is even causing bugs from time to time (see #4580).

**How does this PR accomplish the above?:**

Replace calls to `sqlite3` by calls to `pihole-FTL sqlite3`.

We also remove `sqlite3` as explicit dependency from the installer. Users can always use `pihole-FTL sqlite3` (`pihole-FTL sql` for short) to get the most recent SQLite3 engine embedded into FTL. In current development, this has all the features user expect, including auto-completion and history. We also add convenience features such as `pihole-FTL sql -h ...` for more human-friendly table printing that is not present in the official `sqlite3` package.

I had to rewrite some parts in gravity as the logic was incorrect. Using our embedded SQLite3 engine, this was revealed as it was complaining about a lot of foreign key violations because our embedded version is sufficiently new (compared to the system-provided ones) that foreign key enforcement is a thing.

The issue is that we are creating the database and inject `gravity` domains as the first thing. However, each gravity domain refers to an `adlist` entry and, since this table was still empty, each insertion triggered a violation. This is now fixed by ensuring we make the entire database ready before inserting the gravity domains in a final step.

Three new `DELETE FROM ... WHERE NOT IN (...)` statements in the gravity copying script removes orphaned entries which could be in the database when users interacted with the database manually. We remove these orphans as their presence would also trigger foreign key violations when the domains/adlists/clients they refer to are gone.

**What documentation changes (if any) are needed to support this PR?:**

None

2022-01-30 10:20 UTC, DL6ER commented
I should have caught all of them. The only remainders of something not starting in `pihole-FTL sqlite3` seems to be comments and PHP:
![Screenshot from 2022-01-30 11-19-24](https://user-images.githubusercontent.com/16748619/151695713-1c9bde01-b6a8-4b74-8a83-7d3cf36df971.png)

2022-01-30 20:07 UTC, DL6ER commented
Confirmed working by OP in https://github.com/pi-hole/pi-hole/issues/4580#issuecomment-1025108547

2022-01-30 22:59 UTC, PromoFaux submitted a review, later dismissed
Also confirmed working by me, I just got distracted by another bug!

2022-01-31 06:12 UTC, yubiuser requested changes
https://github.com/pi-hole/pi-hole/blob/e80a7731c98d3ee1c03e0fd62621b49a4c621b43/automated%20install/basic-install.sh#L335

Remove it from RPM distros as well

2022-02-02 19:04 UTC, yubiuser approved these changes

2022-02-02 20:27 UTC, yubiuser commented
Build on CentOS 8 failed due to EOL.
https://stackoverflow.com/questions/70926799/centos-through-vm-no-urls-in-mirrorlist

Adding 

```
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* &&\
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
```

Could fix the issue (see answer 2 from above). Or we switch to CentOS Steam

2022-02-02 20:38 UTC, DL6ER commented
@dschaper How do we want to proceed here? First remove or fix CentOS 8 and merge the modified test instructions into this PR or merge despite the failed tests?

2022-02-03 04:06 UTC, dschaper commented
Merge this with admin override. Then remove the CentOS 8 tests?

2022-02-03 04:45 UTC, merged