Do not update package cache on install/upgrade
pi-hole/pi-hole pull request #5502
Opened 2023-11-26 08:37 UTC by DL6ER

# What does this implement/fix?

Do not update package cache on install/upgrade. It takes quite a long time and we don't do this for `dnf`/`yum` either.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2023-11-26 12:50 UTC, yubiuser reviewed
Do we wan to keep `notify_package_updates_available()`?

2023-11-26 16:29 UTC, DL6ER commented
No, I think this is only due to the artificially clean environment of a CI container. No real OS will know nothing about their sources. We neither support installing into naked container (or do we?).

If we do, the logic needs to be changed to use `apt-cache` to check if we have install candidates for packages and, if not, then indeed run `apt update`.

Converting this  PR to draft and doing this later...

2023-11-27 21:08 UTC, yubiuser requested changes
This is not a good place to put the update function.  It will update the cache 3 times in a row on new installs as `install_dependent_packages()` is called 3 times during installation and usually not empty.

2024-05-12 07:50 UTC, DL6ER commented
@yubiuser I simplified the approach

2024-05-12 12:42 UTC, PromoFaux commented
I'm a little confused as to the logic here...

`PKG_MANAGER_UPDATE` is defaulted to false. once `update_package_cache` runs, it is set to true and so subsequent calls of this function will not do the package update. 

What I can't see here is how we get ourselves into a situation where `update_package_cache` is run more than once... Sure, it would run each time one runs `pihole -up`... but each time that is run the value of `PKG_MANAGER_UPDATE` will be false... and therefore the `update_package_cache` function will run in full.

Maybe I'm just being dense... but what is the goal here?

2024-05-12 13:10 UTC, closed without merging

2024-05-12 13:10 UTC, DL6ER commented
I think this PR has been changed too often and it was abandoned too often, too, to reproduce its original intention. Closing l.