Explicitly migrate from v5 to v6
pi-hole/pi-hole pull request #5830
Opened 2024-12-21 06:13 UTC by DL6ER

# What does this implement/fix?

**Explicitly** migrate config from v5 to v6 instead of :crossed_fingers: that this is done automagically on the first (re)start of `pihole-FTL`. We have seen at least [one report](https://discourse.pi-hole.net/t/broken-installation/74638/24) where a race-collision was able to destroy that hope.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-12-21 20:16 UTC, yubiuser submitted a review, later dismissed

2024-12-23 07:59 UTC, DL6ER commented
Tested on various VMs after #5832 had been merged.

![VirtualBox_Debian_23_12_2024_08_57_07](https://github.com/user-attachments/assets/d89dd00b-52ad-4905-a92a-b112160e909e)

The last commit adds details about the migration which seems a useful thing to do:

![VirtualBox_Debian_23_12_2024_08_56_47](https://github.com/user-attachments/assets/781281f0-f717-4f9a-8f62-f5ced76f70f2)

2024-12-23 07:59 UTC, DL6ER commented
This PR is now ready for review

2024-12-23 08:19 UTC, DL6ER commented
Tests need to re restarted once the FTL PR has been merged.

2025-01-06 15:57 UTC, yubiuser commented
On a fresh v5 ->v6 update there is one place where it tries to set ownership of `pihole.toml` before it is created.

```
    setupVars.conf:DHCP_LEASETIME -> Not set
    setupVars.conf:DHCP_IPv6 -> Not set
    setupVars.conf:DHCP_RAPID_COMMIT -> Not set
    setupVars.conf:queryLogging -> Not set
    setupVars.conf:GRAVITY_TMPDIR -> Not set
    setupVars.conf:WEB_PORTS -> Not set
    Moved /etc/pihole/setupVars.conf to /etc/pihole/migration_backup_v6/setupVars.conf
    setupVars.conf migration complete
    Moving /etc/pihole/custom.list to /etc/pihole/migration_backup_v6/custom.list
    Config initialized with webserver ports 80 (HTTP) and 443 (HTTPS), IPv6 support is enabled
    Wrote config file:
     - 151 total entries
     - 145 entries are default
     - 6 entries are modified
     - 0 entries are forced through environment
    Failed to change ownership of "/etc/pihole/pihole.toml" to pihole:pihole (999:1000): No such file or directory
    Config file written to /etc/pihole/pihole.toml  [i] Testing if systemd-resolved is enabled
    ```

2025-01-06 17:33 UTC, DL6ER commented
@yubiuser both should be addressed now

2025-01-08 11:10 UTC, yubiuser commented on automated install/basic-install.sh
> +    printf "  %b %s...\\n" "${INFO}"
```suggestion
    printf "  %b %s...\\n" "${INFO}" "${str}"
```

Otherwise it looks like

```
  [✓] Disabling lighttpd service...
  [i] ...
  [✓] Migrating Pi-hole configuration to version 6
    Migrating config to Pi-hole v6.0 format
```

2025-01-08 11:10 UTC, yubiuser commented on automated install/basic-install.sh
> +        printf "  %b %s\\n" "${TICK}" "${str}"
```suggestion
        printf "%b  %b %s\\n" "${OVER}" "${TICK}" "${str}"
```

2025-01-08 11:10 UTC, yubiuser commented on automated install/basic-install.sh
> +        printf "  %b %s\\n" "${CROSS}" "${str}"
```suggestion
        printf "%b  %b %s\\n" "${OVER}" "${CROSS}" "${str}"
```

2025-01-09 16:45 UTC, yubiuser requested changes

2025-01-09 16:45 UTC, yubiuser commented on automated install/basic-install.sh
> +    printf "  %b %s...\\n" "${INFO}" "${str}"
```suggestion
    printf "  %b %s..." "${INFO}" "${str}"
```

```
  [✓] Disabling lighttpd service...
  [i] Migrating Pi-hole configuration to version 6...
  [✓] Migrating Pi-hole configuration to version 6
    Migrating config to Pi-hole v6.0 format
```

2025-01-09 17:53 UTC, yubiuser approved these changes

2025-01-09 18:09 UTC, PromoFaux commented on automated install/basic-install.sh
> +    FTLoutput=$(pihole-FTL migrate v6)
In the docker container - we move the conf files already - I suppose it is also worth running this new command too? 

I note the comments say the file will be created with defaults unless changes made in config files... will it also take into account environment variables?

2025-01-09 18:11 UTC, DL6ER commented on automated install/basic-install.sh
> +    FTLoutput=$(pihole-FTL migrate v6)
Re env vars: Yes, but only in new v6 style. The old v5 env vars are unknown to FTL.

2025-01-09 18:11 UTC, DL6ER commented on automated install/basic-install.sh
> +    FTLoutput=$(pihole-FTL migrate v6)
Re should it run in `docker`land?: Absolutely!

2025-01-09 18:18 UTC, PromoFaux commented on automated install/basic-install.sh
> +    FTLoutput=$(pihole-FTL migrate v6)
Yeah, wouldn't expect v5 environment variables to be understood/migrated!

2025-01-09 18:39 UTC, merged

2025-01-13 18:16 UTC, PromoFaux commented on automated install/basic-install.sh
> +    printf "%b" "${FTLoutput}" | sed 's/^/    /'
I really love this, will be implementing it in places on the Docker image - something that has annoyed me for a while with Gravity output for example