Disable lighttpd if found
pi-hole/pi-hole pull request #5835
Opened 2024-12-23 08:33 UTC by DL6ER

# What does this implement/fix?

Lighttpd is not needed anymore, so let's disable it to avoid conflicts concerning (at least) port 80. We keep all the configuration files in place, so the user can re-enable it if needed and can then also decide how they want to assign ports. Pi-hole v6.0 is a major release and such a "soft" breaking change is fine. In the end, the vast majority of Pi-hole users will only be using `lighttpd` for the Pi-hole web interface which makes it a useless service for them with v6.0+.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-12-23 13:07 UTC, PromoFaux commented
I have mixed feelings about this - somehow I think it should be provided as an option to the user via a dialog or some other interactive check, while still defaulting to this behaviour. 

I agree with your assessment that the majority of users are _probably_ only using `lighttpd` for Pi-hole, but at this stage there could be untold numbers of people who have gone "Well, Pi-hole has installed `lighttpd`, and I also want a webserver for another project - so I will use that" - those will be the people that make the most noise

2024-12-23 17:43 UTC, DL6ER commented
I do get your point but the upgrade process is meant to run "unattended", i.e., it won't show any dialogs. We can change that but make sure to show the dialog *very* early, actually before doing anything. I don't think we can actually show it before pulling the repos. My point here is the high likeliness that users run an update cronjob which would faild hard at any kind of dialog. Unless there is a reliable way to detect this non-interactivity and then assume a Yes on this dialog? What do you think?

2024-12-23 18:22 UTC, DL6ER commented
![grafik](https://github.com/user-attachments/assets/d9ede4bc-0470-4678-b167-84b368388c93)

2024-12-23 22:25 UTC, PromoFaux requested changes

2024-12-23 22:25 UTC, PromoFaux commented on automated install/basic-install.sh
> +            --title "Pi-hole v6.0 does no longer need lighttpd" \
```suggestion
            --title "Pi-hole v6.0 no longer uses lighttpd" \
```

Just to un-german the grammar

2024-12-24 00:33 UTC, rdwebdesign submitted a review, later dismissed

2024-12-24 00:33 UTC, rdwebdesign commented on automated install/basic-install.sh
> +            --yesno "Pi-hole v6.0 has its own embedded web server so lighttpd is no longer needed *unless* you have custom configurations. In this case, you can opt-out of disabling lighttpd and piho
Also, I suggest some line breaks to add a little space and increase readability:

 ```suggestion
            --yesno "\\n\\nPi-hole v6.0 has its own embedded web server so lighttpd is no longer needed *unless* you have custom configurations.\\n\\nIn this case, you can opt-out of disabling lighttpd and pihole-FTL will try to bind to an alternative port such as 8080.\\n\\nDo you want to disable lighttpd (recommended)?" "${r}" "${c}"
```
![image](https://github.com/user-attachments/assets/8d371e29-25db-47a6-ba9c-674413269b75)

2024-12-30 11:24 UTC, AyanokojiK1yotaka commented
It would be helpful to provide a mechanism for users to uninstall Lighttpd, as the majority of users may not need this service. The only exception would be those who use Lighttpd for specific purposes, such as acting as a reverse proxy or load balancing.

2024-12-30 12:45 UTC, PromoFaux commented
Testing this with `pihole checkout`...

Selecting yes works as expected - `lighttpd` is disabled and `pihole-FTL` binds to port 80
Selecting no throws the following:

![image](https://github.com/user-attachments/assets/9afc2591-8fc9-4d7f-a177-1d449358fa7f)

Relevant `bash -x` output:

```txt
+ systemctl is-enabled systemd-resolved
+ printf '  %b %b Testing if systemd-resolved DNSStub-Listener is active' '\r' '[i]'
 [i] Testing if systemd-resolved DNSStub-Listener is active+ grep -E '#?DNSStubListener=yes' /etc/systemd/resolved.conf
+ printf '%b  %b Systemd-resolved does not need to be restarted\n' '\r' '[i]'
  [i] Systemd-resolved does not need to be restarted
+ disableLighttpd
+ [[ -t 0 ]]
+ dialog --no-shadow --keep-tite --title 'Pi-hole v6.0 no longer uses lighttpd' --yesno '\n\nPi-hole v6.0 has its own embedded web server so lighttpd is no longer needed *unless* you have custom configurations.\n\nIn this case, you can opt-out of disabling lighttpd and pihole-FTL will try to bind to an alternative port such as 8080.\n\nDo you want to disable lighttpd (recommended)?' 20 70
```

2024-12-30 14:36 UTC, DL6ER commented
Ah, sure, `set -e` again. Should be fixed.

2024-12-30 15:24 UTC, PromoFaux approved these changes
Now working as expected when selecting no.

```
root@adam-test-droplet:~# netstat -tulpn | grep pihole-FTL
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      13696/pihole-FTL    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      13696/pihole-FTL    
tcp6       0      0 :::8080                 :::*                    LISTEN      13696/pihole-FTL    
tcp6       0      0 :::443                  :::*                    LISTEN      13696/pihole-FTL    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           13696/pihole-FTL    
udp        0      0 0.0.0.0:123             0.0.0.0:*                           13696/pihole-FTL    
udp6       0      0 :::123                  :::*                                13696/pihole-FTL    
root@adam-test-droplet:~# netstat -tulpn | grep lighttpd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12435/lighttpd      
tcp6       0      0 :::80                   :::*                    LISTEN      12435/lighttpd 
```

And as expected with yes:

```
root@adam-test-droplet:~# netstat -tulpn | grep pihole-FTL
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      13736/pihole-FTL    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13736/pihole-FTL    
tcp6       0      0 :::443                  :::*                    LISTEN      13736/pihole-FTL    
tcp6       0      0 :::80                   :::*                    LISTEN      13736/pihole-FTL    
udp        0      0 0.0.0.0:53              0.0.0.0:*                           13736/pihole-FTL    
udp        0      0 0.0.0.0:123             0.0.0.0:*                           13736/pihole-FTL    
udp6       0      0 :::123                  :::*                                13736/pihole-FTL    
root@adam-test-droplet:~# netstat -tulpn | grep lighttpd
root@adam-test-droplet:~# 
```

2024-12-30 16:01 UTC, DL6ER commented
@AyanokojiK1yotaka completely removing lighttpd automatically seems too much IMO given that this makes it (a bit) more complicated to get it going again if needed. New v6 installations won't have it from the beginning

2024-12-30 16:01 UTC, merged

2025-01-01 13:00 UTC, yubiuser commented on automated install/basic-install.sh
> +    disableLighttpd
This is placed here unconditionally. It will trigger on each update/checkout. 
We should put it into the migration part (where it is guarded by `if [[ -f "${PI_HOLE_V6_CONFIG}" ]]; then` and additionally check for the presence and enable/disable state of `lighttpd` at all.

2025-01-01 17:57 UTC, DL6ER commented on automated install/basic-install.sh
> +    disableLighttpd
https://github.com/pi-hole/pi-hole/pull/5849